name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release with Changesets
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for changesets
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build packages
        run: make build
      
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called "release" which does a build before calling changeset publish
          publish: npm run release
          title: "Release: Version Packages"
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      
      - name: Create git tags for published packages
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "Published packages:"
          echo "${{ steps.changesets.outputs.publishedPackages }}"
          
          # Create tags for each published package
          echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '.[] | "\(.name)@\(.version)"' | while read tag; do
            echo "Creating tag: $tag"
            git tag "$tag"
            git push origin "$tag"
          done
      
      - name: Send notification on success
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "🎉 Packages published successfully!"
          echo "Published packages: ${{ steps.changesets.outputs.publishedPackages }}"
